### ISSUE TITLE
creating messages with two quotes doesn't work (JS errors out)

### ISSUE THREAD

**Issue by ThePerkinrex** [HermesMessenger/Hermes#48]

**Comment by spaceface777** [comment]
I don't think this is an issue as users shouldn't be able to make messages with two quotes in the first place.

**Comment by spaceface777** [comment]
I'm changing the quoting process to delete any quotes already in the message, so that the user can't accidentally have two quotes in one message.

(If I click `quote` on `Message A` and then click `quote` on `Message B`, then the quote for `Message A` will get deleted and the message will only have the quote for `Message B`)
