### ISSUE TITLE
Setting Up Second Hermes Raspberry Pi Server 

### ISSUE THREAD

**Issue by Tloru** [HermesMessenger/Hermes#67]
Frequently, I see that the hermes server is down. I own a rapsberry pi and would like to set it up to run with the main hermes server in Spain (I live in SE Asia). This would reduce the points of failure and make the server more reliable down the road.

**Comment by spaceface777** [comment]
It would be great to have another server (the more the better) but we still don't have the code to decentralize the servers finished, so the two databases wouldn't be syncronized. However, if you want to create your own server, you can use [the instructions in the wiki](https://github.com/HermesMessenger/Hermes/wiki) to create your own.

**Comment by Tloru** [comment]
Ok. what work needs to be done to make the decentralized code?

**Comment by spaceface777** [comment]
I'm not sure how we're going to do this yet, but I think @ThePerkinrex has started working on it so he would be a better person to ask.

**Comment by ThePerkinrex** [comment]
The decentralizing code is divided in two parts, the HADaemon (A separate repo) & the HA functions on the server.
The HADaemon makes the server it's running on overtake the main one if it's down
The HA functions in the server(W.I.P) are going to connect the databases of the servers running, the main server is going to relay the API calls down to the secondary servers, so that their databases are updated

**Comment by Tloru** [comment]
Ah, I see. Is there anything *specifically* I can work on to help?

**Comment by ThePerkinrex** [comment]
This is done, because to connect the databases we're just going to use the Cassandra nodes with replication
