### ISSUE TITLE
Quoting messages doesn't work in some situations

### ISSUE THREAD

**Issue by Tloru** [HermesMessenger/Hermes#81]
I was chatting with @spaceface777 on Hermes (the testing branch) when he quoted one of my messages and it turned out weird for both of us. After some investigation, it looks like when you quote a message containing a quote from another person, followed by another `'`, the message doesn't quote correctly. i.e:

```
user-a: How are you doing?
user-b: "user-a: How are you doing?" I'm doing fine!
```
(note the ominous `'` in the `I'm` after the quote...)  
what should happen when user a quotes user b:
```
user-a: "user-b: I'm doing fine!" Great
```
what actually happens:  
(idk but it doesn't look right...)

hope this helps

**Comment by ThePerkinrex** [comment]
I saw the messages that caused problems, the special thing that they had is the semicolon, that may be the issue

**Comment by spaceface777** [comment]
The issue is because of the *colon* (*not* semicolon) character in the regex. The regex was splitting the quote at the last colon in the string, so it can't find the quoted user as it doesn't exist. 

The fix is easy: just make the regex match the first semicolon (using lazy matching, or `?`)

***

![image](https://user-images.githubusercontent.com/12110214/53906036-399f2780-404a-11e9-8ae7-88414e1b905f.png)  How the regexp currently works

![image](https://user-images.githubusercontent.com/12110214/53905968-107e9700-404a-11e9-8cd9-aa0fa287d8e1.png)  How the regexp works after the fix (with lazy matching)

**Comment by ThePerkinrex** [comment]
@spaceface777 weeell, I didn't remember which was the colon and semicolon
